// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewQuestion struct {
	QuizID   string   `json:"quizID"`
	Question string   `json:"question"`
	Answer   string   `json:"answer"`
	Options  []string `json:"options"`
}

type NewQuiz struct {
	Title       string `json:"title"`
	Description string `json:"description"`
}

type NewUser struct {
	Username  string `json:"username"`
	Email     string `json:"email"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type Query struct {
}
