// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model
// import "time"

type User struct {
	ID        string     `json:"id"`
	Username  string     `json:"username"`
	Email     string     `json:"email"`
	Password  string     `json:"password"`
	FirstName string     `json:"firstName"`
	LastName  string     `json:"lastName"`
	// CreatedAt time.Time  `json:"createdAt"`
	// UpdatedAt time.Time  `json:"updatedAt"`
	// DeletedAt *time.Time `json:"-" pg:",soft_delete"`
}