apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quiz
  template:
    metadata:
      labels:
        app: quiz
    spec:
      containers:
        - name: quiz
          image: your-dockerhub/quiz:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: quiz-config